#pragma config(Sensor, in1,    clawPOT,        sensorPotentiometer)
#pragma config(Motor,  port2,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/** - DOC STRING -
*
* Toggle Button Program for VRC Remote Control Operation
* 	- one button pressed once opens claw
* 	- same button pressed again closes claw
*
* Program Adapted From:
*   - "Advanced Programming in the VEX Environment" by Peter Johnson on 1 March 2008
*   - from Northrop Grumman slide-show presentation Link: http://slideplayer.com/slide/6837271/
*
*/

//-----------------------------------------------------------------------------------------	VARS

int claw_closed = 1;
int claw_changing = 0;            //	change in progress  var -- is the claw changing
				  //	states from "closed" to "open" or vice-versa

int clawPOT_Val = SensorValue[clawPOT];
int clawPOT_openThres = 300;	    	//	clawPOT threshold value indicating open claw
int clawPOT_closeThres = 3400; 		//	clawPOT threshold value indicating closed claw

int clawPower = 120;			//	default power to claw motor


//-----------------------------------------------------------------------------------------	TOGGLE BUTTON CODE

void claw_func(){
	if(vexRT[Btn8D] == 1){

		if((claw_changing == 0) &&
			((clawPOT_Val < clawPOT_openThres) || (clawPOT_Val > clawPOT_closeThres))){
			if(claw_closed){
				// open it
				//  --> might need to add: while(SensorValue[clawPOT] > openThres){
				motor[claw] = clawPower;
			}
			else{
				// close it
				// --> might need to add: while(SensorValue[clawPOT] < closeThres){
				motor[claw] = -clawPower;
			}
			// update status
			claw_closed = !claw_closed;
			claw_changing = 1;
		}

		else if(claw_changing == 1){
			if(!((clawPOT_Val < clawPOT_openThres) || (clawPOT_Val > clawPOT_closeThres))){
				//	reset and start Timer T1
				clearTimer(T1);
				claw_changing = 2;
			}
		}

		else if(claw_changing == 2){
			if((clawPOT_Val < clawPOT_openThres) || (clawPOT_Val > clawPOT_closeThres)){
				// opps, got another press within the timeout period
				claw_changing = 1;
			}
			else{
				if(time1[T1] > time100[T1]){
					claw_changing = 0;
					clearTimer(T1);}
				}
		}
	}
}

//++++++++++++++++++++++++++++++++++++++++ MAIN ++++++++++++++++++++++++++++++++++++++++

task main()
{
	while(true){
		claw_func();
	}
}
